[package]
name = "png"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0.30"

[workspace]
resolver = "2"
members = [
  "examples/viewer"
]

[workspace.dependencies.png]
package = "png"
path = "./"
